### ISSUE TITLE
Potential issue regarding mastery spam

### ISSUE THREAD

**Issue by osori** [Xerath-Scripts-Inc/Super-Secret-Xerath-Project#3]
nah just kidding it's perfect, no issue at all

https://github.com/Xerath-Scripts-Inc/Super-Secret-Xerath-Project/blob/9c9b11257afbbef85abb17bc16ff81102bc01e1b/super_secret_xerath_script.java#L7

_"Superb, captivating, and extraordinary."_ - The New York Times
_"Meticulously designed."_ - USA Today

**Comment by klmui** [comment]
Wow! I'm glad the New York Times + USA Today like our script :D. Please let me know if you are willing to invest in Xerath Scripts Inc.
